import Problem_01 from "./Problem_01";
import Problem_02 from "./Problem_02";
import Problem_03 from "./Problem_03";
import Problem_04 from "./Problem_04";
import Problem_05 from "./Problem_05";
import Problem_06 from "./Problem_06";
import Problem_07 from "./Problem_07";
import Problem_08 from "./Problem_08";
import Problem_09 from "./Problem_09";
import Problem_10 from "./Problem_10";
import Problem_11 from "./Problem_11";
import Problem_12 from "./Problem_12";

const problems = [
  {
    number: 1,
    title: "Multiples of 3 and 5",
    description: "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.",
    component: Problem_01,
    props: { initialMaxNum: 1000 },
  },
  {
    number: 2,
    title: "Even Fibonacci numbers",
    description: "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.",
    component: Problem_02,
    props: { initialMaxNum: 4000000 },
  },
  {
    number: 3,
    title: "Largest prime factor",
    description: "The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number 600851475143?",
    component: Problem_03,
    props: { initialNum: 600851475143 },
  },
  {
    number: 4,
    title: "Largest palindrome product",
    description: "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99. Find the largest palindrome made from the product of two 3-digit numbers.",
    component: Problem_04,
    props: { initialDigits: 3 },
  },
  {
    number: 5,
    title: "Smallest multiple",
    description: "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder. What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?",
    component: Problem_05,
    props: { initialMaxNum: 20 },
  },
  {
    number: 6,
    title: "Sum square difference",
    description: "The sum of the squares of the first ten natural numbers is 385, The square of the sum of the first ten natural numbers is 3025, Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 2640. Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.",
    component: Problem_06,
    props: { initialMaxNum: 100 },
  },
  {
    number: 7,
    title: "10 001st Prime",
    description: "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13. What is the 10 001st prime number?",
    component: Problem_07,
    props: { initialNth: 10001 },
  },
  {
    number: 8,
    title: "Largest Product in a Series",
    description: "The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832. Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product? Full number: https://projecteuler.net/problem=8",
    component: Problem_08,
    props: { 
      numStr: "73167176531330624919225119674426574742355349194934969835203127745063262395783180169848018694788518438586156078911294949545950173795833195285320880551112540698747158523863050715693290963295227443043557668966489504452445231617318564030987111217223831136222989342338030813533627661428280644448664523874303589072962904915604407723907138105158593079608667017242712188399879790879227492190169972088809377665727333001053367881220235421809751254540594752243525849077116705560136048395864467063244157221553975369781797784617406495514929086256932197846862248283972241375657056057490261407972968652414535100474821663704844031998900088952434506585412275886668811642717147992444292823086346567481391912316282458178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450",
      initialDigits: 13,
    },
  },
  {
    number: 9,
    title: "Special Pythagorean Triplet",
    description: "A Pythagorean triplet is a set of three natural numbers, a < b < c, for which, a2 + b2 = c2. For example, 3sq + 4sq = 9 + 16 = 25 = 5sq. There exists exactly one Pythagorean triplet for which a + b + c = 1000. Find the product abc.",
    component: Problem_09,
    props: { initialSum: 1000 },
  },
  {
    number: 10,
    title: "Summation of Primes",
    description: "The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17. Find the sum of all the primes below two million.",
    component: Problem_10,
    props: { initialMaxNum: 2000000 },
  },
  {
    number: 11,
    title: "Largest Product in a Grid",
    description: "In the 20×20 grid below, four numbers along a diagonal line have been marked in red. The product of these numbers is 26 × 63 × 78 × 14 = 1788696. What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid? The grid: https://projecteuler.net/problem=11",
    component: Problem_11,
    props: {
      initialDigits: 4,
      initialGrid: [
        [8, 2, 22, 97, 38, 15, 0, 40, 0, 75, 4, 5, 7, 78, 52, 12, 50, 77, 91, 8],
        [49, 49, 99, 40, 17, 81, 18, 57, 60, 87, 17, 40, 98, 43, 69, 48, 4, 56, 62, 0],
        [81, 49, 31, 73, 55, 79, 14, 29, 93, 71, 40, 67, 53, 88, 30, 3, 49, 13, 36, 65],
        [52, 70, 95, 23, 4, 60, 11, 42, 69, 24, 68, 56, 1, 32, 56, 71, 37, 2, 36, 91],
        [22, 31, 16, 71, 51, 67, 63, 89, 41, 92, 36, 54, 22, 40, 40, 28, 66, 33, 13, 80],
        [24, 47, 32, 60, 99, 3, 45, 2, 44, 75, 33, 53, 78, 36, 84, 20, 35, 17, 12, 50],
        [32, 98, 81, 28, 64, 23, 67, 10, 26, 38, 40, 67, 59, 54, 70, 66, 18, 38, 64, 70],
        [67, 26, 20, 68, 2, 62, 12, 20, 95, 63, 94, 39, 63, 8, 40, 91, 66, 49, 94, 21],
        [24, 55, 58, 5, 66, 73, 99, 26, 97, 17, 78, 78, 96, 83, 14, 88, 34, 89, 63, 72],
        [21, 36, 23, 9, 75, 0, 76, 44, 20, 45, 35, 14, 0, 61, 33, 97, 34, 31, 33, 95],
        [78, 17, 53, 28, 22, 75, 31, 67, 15, 94, 3, 80, 4, 62, 16, 14, 9, 53, 56, 92],
        [16, 39, 5, 42, 96, 35, 31, 47, 55, 58, 88, 24, 0, 17, 54, 24, 36, 29, 85, 57],
        [86, 56, 0, 48, 35, 71, 89, 7, 5, 44, 44, 37, 44, 60, 21, 58, 51, 54, 17, 58],
        [19, 80, 81, 68, 5, 94, 47, 69, 28, 73, 92, 13, 86, 52, 17, 77, 4, 89, 55, 40],
        [4, 52, 8, 83, 97, 35, 99, 16, 7, 97, 57, 32, 16, 26, 26, 79, 33, 27, 98, 66],
        [88, 36, 68, 87, 57, 62, 20, 72, 3, 46, 33, 67, 46, 55, 12, 32, 63, 93, 53, 69],
        [4, 42, 16, 73, 38, 25, 39, 11, 24, 94, 72, 18, 8, 46, 29, 32, 40, 62, 76, 36],
        [20, 69, 36, 41, 72, 30, 23, 88, 34, 62, 99, 69, 82, 67, 59, 85, 74, 4, 36, 16],
        [20, 73, 35, 29, 78, 31, 90, 1, 74, 31, 49, 71, 48, 86, 81, 16, 23, 57, 5, 54],
        [1, 70, 54, 71, 83, 51, 54, 69, 16, 92, 33, 48, 61, 43, 52, 1, 89, 19, 67, 48],
      ],
    },
  },
  {
    number: 12,
    title: "Highly Divisible Triangular Number",
    description: "The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ... Let us list the factors of the first seven triangle numbers: 1:1; 3:1,3; 6:1,2,3,6; 10:1,2,5,10; 15:1,3,5,15; 21:1,3,7,21; 28:1,2,4,7,14,28; We can see that 28 is the first triangle number to have over five divisors. What is the value of the first triangle number to have over five hundred divisors?",
    component: Problem_12,
    props: { initialDivisors: 500 },
  },
];

export default problems;