import Problem_01 from "./Problem_01";
import Problem_02 from "./Problem_02";
import Problem_03 from "./Problem_03";
import Problem_04 from "./Problem_04";
import Problem_05 from "./Problem_05";
import Problem_06 from "./Problem_06";
import Problem_07 from "./Problem_07";
import Problem_08 from "./Problem_08";

const problems = [
  {
    number: 1,
    title: "Multiples of 3 and 5",
    description: "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.",
    component: Problem_01,
    props: { maxNum: 1000 },
  },
  {
    number: 2,
    title: "Even Fibonacci numbers",
    description: "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.",
    component: Problem_02,
    props: { maxNum: 4000000 },
  },
  {
    number: 3,
    title: "Largest prime factor",
    description: "The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number 600851475143?",
    component: Problem_03,
    props: { num: 600851475143 },
  },
  {
    number: 4,
    title: "Largest palindrome product",
    description: "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99. Find the largest palindrome made from the product of two 3-digit numbers.",
    component: Problem_04,
    props: { digits: 3 },
  },
  {
    number: 5,
    title: "Smallest multiple",
    description: "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder. What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?",
    component: Problem_05,
    props: { maxNum: 20 },
  },
  {
    number: 6,
    title: "Sum square difference",
    description: "The sum of the squares of the first ten natural numbers is 385, The square of the sum of the first ten natural numbers is 3025, Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 2640. Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.",
    component: Problem_06,
    props: { maxNum: 100 },
  },
  {
    number: 7,
    title: "10 001st Prime",
    description: "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13. What is the 10 001st prime number?",
    component: Problem_07,
    props: { nth: 10001 },
  },
  {
    number: 8,
    title: "Largest Product in a Series",
    description: "The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832. Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?",
    component: Problem_08,
    props: { 
      numStr: "73167176531330624919225119674426574742355349194934969835203127745063262395783180169848018694788518438586156078911294949545950173795833195285320880551112540698747158523863050715693290963295227443043557668966489504452445231617318564030987111217223831136222989342338030813533627661428280644448664523874303589072962904915604407723907138105158593079608667017242712188399879790879227492190169972088809377665727333001053367881220235421809751254540594752243525849077116705560136048395864467063244157221553975369781797784617406495514929086256932197846862248283972241375657056057490261407972968652414535100474821663704844031998900088952434506585412275886668811642717147992444292823086346567481391912316282458178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450",
      digits: 13,
    },
  }
];

export default problems;