import Problem from "./components/Problem";
import Problem_01 from "./problems/Problem_01";
import Problem_02 from "./problems/Problem_02";
import Problem_03 from "./problems/Problem_03";

function App() {
  return (
    <div className="App pb-16 w-screen min-h-screen bg-black mx-auto">
      <div className="pt-4 mx-auto max-w-lg flex flex-col">
        <h1 className="mt-3 mb-4 text-5xl text-green-500 text-center font-Audiowide drop-shadow-[0_0_15px_rgba(34,197,94,0.9)]">
          Project Euler
        </h1>
        <Problem 
          number={1} 
          title="Multiples of 3 and 5" 
          description="If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000." 
        />
        <Problem_01 maxNum={1000} />
        <Problem 
          number={2} 
          title="Even Fibonacci numbers" 
          description="Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms." 
        />
        <Problem_02 maxNum={4000000} />
        <Problem 
          number={3}
          title="Largest prime factor"
          description="The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number 600851475143?"
        />
        <Problem_03 num={600851475143} />
      </div>
    </div>
  );
}

export default App;
